# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-17 04:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('course', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Container',
            fields=[
                ('id_container', models.CharField(max_length=250, primary_key=True, serialize=False)),
                ('name_container', models.CharField(max_length=250)),
                ('port_number_80_container', models.CharField(max_length=50)),
                ('port_number_3306_container', models.CharField(max_length=50)),
                ('base_image_container', models.CharField(max_length=250)),
                ('address_volume_db_host_container', models.CharField(max_length=250)),
                ('ip_address_container', models.CharField(max_length=250)),
                ('running_container', models.CharField(max_length=250)),
                ('associated_course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.Course')),
            ],
        ),
    ]
