# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-17 03:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AcademicPeriod',
            fields=[
                ('id_academic_period', models.CharField(max_length=250, primary_key=True, serialize=False)),
                ('name_academic_period', models.CharField(max_length=250)),
            ],
        ),
    ]
