# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-17 04:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('period', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id_course', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('code_course', models.CharField(choices=[('750001M', '750001M'), ('750017M', '750017M')], default=0, max_length=50)),
                ('name_course', models.CharField(choices=[('Algoritmia y Programación', 'Algoritmia y Programación'), ('Métodos Numéricos', 'Métodos Numéricos')], default=0, max_length=250)),
                ('credits_course', models.CharField(choices=[('3', '3'), ('4', '4')], default=0, max_length=10)),
                ('professor_course', models.CharField(max_length=50)),
                ('group_course', models.CharField(max_length=50)),
                ('programming_language', models.CharField(choices=[('1', 'Python'), ('2', 'Scilab')], default=0, max_length=250)),
                ('period_course', models.CharField(choices=[('01', 'February - June'), ('02', 'August - December')], default=0, max_length=250)),
                ('year_course', models.CharField(choices=[('0', 'Choose your option'), ('2017', '2017'), ('2018', '2018')], default=0, max_length=50)),
                ('academic_period', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='period.AcademicPeriod')),
            ],
        ),
    ]
