# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-17 04:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id_image', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('name_image', models.CharField(max_length=50)),
                ('language_image', models.CharField(max_length=50)),
            ],
        ),
    ]
